set1: FORCE
    iverilog '-Wall' '-g2012' '-DSET1=1' main.v testbench.sv  && vvp a.out

set2: FORCE
    iverilog '-Wall' '-g2012' '-DSET2=1' main.v testbench.sv  && vvp a.out

set3: FORCE
    iverilog '-Wall' '-g2012' '-DSET3=1' main.v testbench.sv  && vvp a.out

set4: FORCE
    iverilog '-Wall' '-g2012' '-DSET4=1' main.v testbench.sv  && vvp a.out

FORCE:;